###
GET http://localhost:3000/reminder/643bd5cada7a761f0332f5ce

###
POST http://localhost:3000/reminder
Content-Type: application/json

{
    "title": "Hi",
    "date": "2023-04-14T18:10:02.381+00:00",
    "user_id" : "507f1f77bcf86cd799439011",
    "description" : "Hello"

}

###
POST http://localhost:3000/register
Content-Type: application/json

{
    "username": "admin",
    "password": "123456",
    "ada_key" : ""
}

###


POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "admin",
    "password": "123456"
}

###
GET http://localhost:3000/data/tempAll
Content-Type: application/json

{
    "username": "minhthuctp",
    "ada_key": "aio_Rlcq317mWjsW0Y9BX5B1sPPaBqqR"
}

###
POST http://localhost:3000/feeding
Content-Type: application/json

{
    "user_id": "643bd5cada7a761f0332f5ce",
    "hour" : 10,
    "minute" : 11,
    "level" : 1
}
###
GET http://localhost:3000/feeding/643bd5cada7a761f0332f5ce

###
PATCH http://localhost:3000/feeding
Content-Type: application/json

{
    "_id": "644eae5061053e0de38e241c",
    "user_id": "643bd5cada7a761f0332f5ce",
    "hour" : 5,
    "minute" : 4,
    "level" : 4
}